# Generated by Django 3.0.6 on 2020-05-11 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snacks',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snacks_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='snacks',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snacks_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
