# Generated by Django 3.0.6 on 2020-05-12 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20200512_1815'),
        ('snacks', '0003_auto_20200512_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snacks',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snacks', to='menu.Menu'),
        ),
    ]
