# Generated by Django 3.0.6 on 2020-05-10 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0001_initial'),
        ('dinner', '0001_initial'),
        ('breakfast', '0001_initial'),
        ('today_special', '0001_initial'),
        ('snacks', '0001_initial'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='breakfast',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='breakfast.Breakfast'),
        ),
        migrations.AddField(
            model_name='menu',
            name='dinner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dinner.Dinner'),
        ),
        migrations.AddField(
            model_name='menu',
            name='lunch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lunch.Lunch'),
        ),
        migrations.AddField(
            model_name='menu',
            name='snacks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='snacks.Snacks'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(blank=True, default='anything', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='today_special',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='today_special.TodaySpecial'),
        ),
    ]
