# Generated by Django 3.0.6 on 2020-05-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breakfast',
            name='menu',
        ),
        migrations.AddField(
            model_name='breakfast',
            name='menu',
            field=models.ManyToManyField(related_name='breakfast', to='menu.Menu'),
        ),
        migrations.RemoveField(
            model_name='dinner',
            name='menu',
        ),
        migrations.AddField(
            model_name='dinner',
            name='menu',
            field=models.ManyToManyField(related_name='dinner', to='menu.Menu'),
        ),
        migrations.RemoveField(
            model_name='lunch',
            name='menu',
        ),
        migrations.AddField(
            model_name='lunch',
            name='menu',
            field=models.ManyToManyField(related_name='lunch', to='menu.Menu'),
        ),
        migrations.RemoveField(
            model_name='snacks',
            name='menu',
        ),
        migrations.AddField(
            model_name='snacks',
            name='menu',
            field=models.ManyToManyField(related_name='snacks', to='menu.Menu'),
        ),
        migrations.RemoveField(
            model_name='todayspecial',
            name='menu',
        ),
        migrations.AddField(
            model_name='todayspecial',
            name='menu',
            field=models.ManyToManyField(related_name='today_special', to='menu.Menu'),
        ),
    ]
