# Generated by Django 3.0.6 on 2020-05-12 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20200511_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='breakfast',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='dinner',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='lunch',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='snacks',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='today_special',
        ),
    ]
