# Generated by Django 3.0.6 on 2020-05-12 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breakfast', '0003_auto_20200512_1438'),
        ('menu', '0003_auto_20200511_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='breakfast',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='breakfast_inside_menu', to='breakfast.Breakfast'),
        ),
    ]
