# Generated by Django 3.0.6 on 2020-05-20 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20200520_1753'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='menu',
            field=models.ForeignKey(default=True, help_text='Breakfast, Lunch, etc', on_delete=django.db.models.deletion.CASCADE, to='menu.Menu'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='item_name',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_name',
            field=models.ManyToManyField(related_name='url', to='menu.Menu'),
        ),
    ]
