# Generated by Django 3.0.6 on 2020-05-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200520_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='item_name',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_name_choice',
            field=models.CharField(blank=True, choices=[('today_special', 'Today_special'), ('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('snacks', 'Snacks'), ('dinner', 'Dinner')], max_length=13, null=True),
        ),
    ]
