# Generated by Django 3.0.6 on 2020-05-20 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20200520_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='item_name_choice',
            new_name='item_name',
        ),
    ]
