# Generated by Django 3.0.6 on 2020-05-20 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='menu',
        ),
    ]
